// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cryczkxgntgtdvvctrnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyeWN6a3hnbnRndGR2dmN0cm51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTE0MDgsImV4cCI6MjA2ODk4NzQwOH0.6MAUdTnGsHN1Ouya9l_fccAW75AaNnMB0mskXMVd2S0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});